# -*- coding: utf-8 -*-
"""rvsp

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1q0FICMfKDqbAAFlBUUTPHE6Et_SYU3wO
"""

import numpy as np
import matplotlib.pyplot as plt
s=np.linspace(-10,10,5) # range of values over which functions are definned 
Mx=np.exp(-(s**2)/2) # moment generating function or spectrum of f(n1)
My=np.exp(-(s**2)/2) # moment generating function or spectrum of f(n2)
Mz=Mx*My # moment generating function or spectrum of f(z)
Ma=np.exp(-s**2)
n=20
c,bin_es=np.histogram(Mz,bins=n,normed=True)
cdf=np.cumsum(c) # cumulative sum or cdf 
#figure,axes=plt.subplots(nrows=2,ncols=2)
Ma=np.exp(-s**2)
# plots of all defined functions
plt.figure()
plt.plot(s,Mx,'g')
plt.xlabel('S-->')
plt.ylabel('Mn1(S)')
plt.title('spectrum of f(n1)')
 
plt.figure()
plt.plot(s,My,'g')
plt.xlabel('S-->')
plt.ylabel('Mn2(S)')
plt.title('spectrum of f(n2)')
 
plt.figure()
plt.plot(s,Mz,'r',label='Mz(s)(simulation)')
plt.plot(s,Ma,'--o',label='Mz(s)(analysis)')
plt.legend(loc='upper right')
plt.xlabel('S-->')
plt.ylabel('Spectra of f(z)')
 
 
plt.figure()
plt.plot(bin_es[1:],cdf/cdf[-1],'y')
plt.title('empirical cdf of Mz(s)')
 
plt.show()